services:
  web:
    container_name: docker-ninja-web-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped