"$schema" = "./node_modules/wrangler/config-schema.json"
main = ".open-next/worker.js"
name = "docker-ninja"
compatibility_date = "2026-06-08"
compatibility_flags = ["asynclocalstorage", "nodejs_compat"]


[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = true