blank_issues_enabled: false
contact_links:
    - name: 💡 New Container Request
      url: https://github.com/vukilis/docker-ninja/discussions/new?category=-request-container&title=Request:
      about: For container requests, please use the Discussions section.
    - name: 🐞 Container Issue Report
      url: https://github.com/vukilis/docker-ninja/issues/new?template=issue-report.md
      about: Create a bug report or report a problem with an application stack.
