services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - './nginx.conf:/etc/nginx/conf.d/default.conf:ro'
      - './html:/usr/share/nginx/html:ro'
    restart: unless-stopped