name: Update App Versions
on:
  schedule:
    - cron: '0 3 * * 0' # Runs once a week
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm install @supabase/supabase-js
      - name: Sync Versions
        run: node sync-versions.mjs
        env:
          CLIENT_URL: ${{ secrets.CLIENT_URL }}
          CLIENT_KEY: ${{ secrets.CLIENT_KEY }}
          CLIENT_TOKEN: ${{ secrets.CLIENT_TOKEN }}